controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - Azimuth_joint
      - Elevation_joint
      - Elbow_joint
      - joint_3
      - wrist_pitch_joint
      - wrist_roll_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: home