// Generated by gencpp from file tag_utils/GetTag.msg
// DO NOT EDIT!


#ifndef TAG_UTILS_MESSAGE_GETTAG_H
#define TAG_UTILS_MESSAGE_GETTAG_H

#include <ros/service_traits.h>


#include <tag_utils/GetTagRequest.h>
#include <tag_utils/GetTagResponse.h>


namespace tag_utils
{

struct GetTag
{

typedef GetTagRequest Request;
typedef GetTagResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTag
} // namespace tag_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tag_utils::GetTag > {
  static const char* value()
  {
    return "3cb26f00cb9a158b9a65f3463d45d1c7";
  }

  static const char* value(const ::tag_utils::GetTag&) { return value(); }
};

template<>
struct DataType< ::tag_utils::GetTag > {
  static const char* value()
  {
    return "tag_utils/GetTag";
  }

  static const char* value(const ::tag_utils::GetTag&) { return value(); }
};


// service_traits::MD5Sum< ::tag_utils::GetTagRequest> should match
// service_traits::MD5Sum< ::tag_utils::GetTag >
template<>
struct MD5Sum< ::tag_utils::GetTagRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tag_utils::GetTag >::value();
  }
  static const char* value(const ::tag_utils::GetTagRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tag_utils::GetTagRequest> should match
// service_traits::DataType< ::tag_utils::GetTag >
template<>
struct DataType< ::tag_utils::GetTagRequest>
{
  static const char* value()
  {
    return DataType< ::tag_utils::GetTag >::value();
  }
  static const char* value(const ::tag_utils::GetTagRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tag_utils::GetTagResponse> should match
// service_traits::MD5Sum< ::tag_utils::GetTag >
template<>
struct MD5Sum< ::tag_utils::GetTagResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tag_utils::GetTag >::value();
  }
  static const char* value(const ::tag_utils::GetTagResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tag_utils::GetTagResponse> should match
// service_traits::DataType< ::tag_utils::GetTag >
template<>
struct DataType< ::tag_utils::GetTagResponse>
{
  static const char* value()
  {
    return DataType< ::tag_utils::GetTag >::value();
  }
  static const char* value(const ::tag_utils::GetTagResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAG_UTILS_MESSAGE_GETTAG_H
