// Generated by gencpp from file tag_utils/GetTagRequest.msg
// DO NOT EDIT!


#ifndef TAG_UTILS_MESSAGE_GETTAGREQUEST_H
#define TAG_UTILS_MESSAGE_GETTAGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tag_utils
{
template <class ContainerAllocator>
struct GetTagRequest_
{
  typedef GetTagRequest_<ContainerAllocator> Type;

  GetTagRequest_()
    : id(0)  {
    }
  GetTagRequest_(const ContainerAllocator& _alloc)
    : id(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::tag_utils::GetTagRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tag_utils::GetTagRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetTagRequest_

typedef ::tag_utils::GetTagRequest_<std::allocator<void> > GetTagRequest;

typedef boost::shared_ptr< ::tag_utils::GetTagRequest > GetTagRequestPtr;
typedef boost::shared_ptr< ::tag_utils::GetTagRequest const> GetTagRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tag_utils::GetTagRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tag_utils::GetTagRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tag_utils::GetTagRequest_<ContainerAllocator1> & lhs, const ::tag_utils::GetTagRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tag_utils::GetTagRequest_<ContainerAllocator1> & lhs, const ::tag_utils::GetTagRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tag_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tag_utils::GetTagRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tag_utils::GetTagRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tag_utils::GetTagRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tag_utils::GetTagRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tag_utils::GetTagRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tag_utils::GetTagRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tag_utils::GetTagRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5e4a7d59c68f74eabcec876a00216aa";
  }

  static const char* value(const ::tag_utils::GetTagRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5e4a7d59c68f74eULL;
  static const uint64_t static_value2 = 0xabcec876a00216aaULL;
};

template<class ContainerAllocator>
struct DataType< ::tag_utils::GetTagRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tag_utils/GetTagRequest";
  }

  static const char* value(const ::tag_utils::GetTagRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tag_utils::GetTagRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
;
  }

  static const char* value(const ::tag_utils::GetTagRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tag_utils::GetTagRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTagRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tag_utils::GetTagRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tag_utils::GetTagRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAG_UTILS_MESSAGE_GETTAGREQUEST_H
