arm_controller:
  type: effort_controllers/JointTrajectoryController
  #type: position_controllers/JointTrajectoryController
  joints:
    - Azimuth_joint
    - Elevation_joint
    - Elbow_joint
    - joint_3
    - wrist_pitch_joint
    - wrist_roll_joint
  gains:
    Azimuth_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Elevation_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

#  constraints:
#    #- goal_time: 0.6
#    - stopped_velocity_tolerance: 0.05
#    - joint_3: {trajectory: 0.05, goal: 0.05}
#    - wrist_pitch_joint: {trajectory: 0.05, goal: 0.05}
#    - wrist_roll_joint: {trajectory: 0.05, goal: 0.05}
#    - Azimuth_joint: {trajectory: 0.05, goal: 0.05}
#    - Elevation_joint: {trajectory: 0.05, goal: 0.05}
#    - Elbow_joint: {trajectory: 0.05, goal: 0.05}
